src/wovnio/wovnphp/Store.php
test/StoreTest.php

Use Fastly!

---

src/wovnio/wovnphp/Headers.php
src/wovnio/wovnphp/Lang.php
src/wovnio/wovnphp/Url.php

Follow phpdoc rule to get benefit from IDE
@see
https://www.sitepoint.com/introduction-to-phpdoc/

Follow phpdoc rule to get benefit from IDE

---

src/wovnio/wovnphp/API.php
src/wovnio/wovnphp/Headers.php
src/wovnio/wovnphp/Lang.php
src/wovnio/wovnphp/Store.php
src/wovnio/wovnphp/Url.php
test/APITest.php
test/HeadersTest.php
test/UrlTest.php

Add support for custom_lang_aliases
Same change with
https://github.com/WOVNio/wovnrb/pull/72
I didn't add explanation to README because this feature is complex and only a few user use the feature.

Add support for custom_lang_aliases

---

src/wovnio/html/HtmlConverter.php
src/wovnio/modified_vendor/SimpleHtmlDom.php
test/html/HtmlConverterTest.php

Remove SimpleHtmlDom MAX_FILE_SIZE limit and ensure WOVN.php does not crash if SimpleHtmlDom::str_get_html returns a boolean instead of an object

Remove SimpleHtmlDom MAX_FILE_SIZE limit and ensure WOVN.php does not

---

wovn_index_sample.php

Add sample for path pattern
When using "path" pattern, the file returns an error because the file is not found.

Add sample for path pattern

---

src/wovn_interceptor.php
src/wovnio/wovnphp/Utils.php
test/UtilsTest.php

Check Content-Type of response if exists.
Stop translation when Content-Type is not html-ish.
Note:
Because when Content-Type is not set, Apache add extra header based on file extension, consider html when the header is not set.

Check Content-Type of response if exists.

---

src/wovnio/html/HtmlConverter.php
src/wovnio/wovnphp/Store.php
test/html/HtmlConverterTest.php

Custom ignore class

---

STATIC_DOC.txt

Add nginx configuration details

NGINX configuration

---

src/wovnio/wovnphp/API.php
test/APITest.php

Add version number and product name on api request for backward compatibility.

Add version number and product name

---

src/wovnio/wovnphp/API.php

We're making a new release and need to change the version in the code.

Change version to 0.1.8 for new release

---

test/unit/APITest.php

Use StoreAndHeadersFactory in API tests

Use StoreAndHeadersFactory in API tests

---

.phpcs.xml
src/wovn_interceptor.php
src/wovnio/utils/request_handlers/AbstractRequestHandler.php
src/wovnio/utils/request_handlers/CurlRequestHandler.php
src/wovnio/utils/request_handlers/FileGetContentsRequestHandler.php
src/wovnio/utils/request_handlers/RequestHandlerFactory.php
src/wovnio/wovnphp/API.php
src/wovnio/wovnphp/Utils.php
test/unit/APITest.php
test/unit/UtilsTest.php
wovn_index_sample.php

Start Applying Coding Standard

---

.phpcs.xml
src/wovnio/wovnphp/SSI.php

Update SSI with coding standard

Update SSI with coding standard

---

.phpcs.xml
test/helpers/EnvFactory.php
test/helpers/StoreAndHeadersFactory.php

Update test factories with coding standard

Update test factories with coding standard

---

.phpcs.xml
src/wovnio/html/HtmlConverter.php
src/wovnio/html/HtmlReplaceMarker.php

Update HtmlReplaceMarker with coding standard

Update HtmlReplaceMarker with coding standard

---

.phpcs.xml
src/wovnio/wovnphp/Url.php

Update URL with coding standard.

Update URL with coding standard

---

.phpcs.xml
test/unit/APITest.php
test/unit/SSITest.php
test/unit/UtilsTest.php

Update ApiTest, SSITest and UtilsTest with coding standards.

Update ApiTest, SSITest and UtilsTest with coding standards

---

.phpcs.xml
test/unit/HeadersTest.php

Update HeadersTest with coding standards.

Update HeadersTest with coding standards

---

.phpcs.xml
src/wovnio/html/HtmlConverter.php
src/wovnio/wovnphp/Store.php
test/unit/html/HtmlConverterTest.php

Update coding standard HtmlConverter
From now on, when fixing a file according to code standard, I will also change the associated test.
I also temporarily excluded the ident rule that can't be fix before changing tab size (`PSR2.Methods.FunctionCallSignature.Indent`).

Update Coding Standard HtmlConverter

---

.phpcs.xml
src/wovnio/wovnphp/Store.php
test/unit/StoreTest.php

Update Store coding standard

---

.phpcs.xml
test/integration/SSIWovnIndexSampleTest.php
test/integration/WovnIndexSampleTest.php

Update WovnIndexSampleTest and SSIWovnIndexSampleTest with coding standard

Update WovnIndexSampleTest and SSIWovnIndexSampleTest with Coding Standard

---

.phpcs.xml
test/unit/UrlTest.php
test/unit/html/HtmlReplaceMakerTest.php

Update UrlTest and HtmlReplaceMarkerTest according to coding standard

Update UrlTest and HtmlReplaceMarkerTest According to Coding Standard

---

.phpcs.xml
test/unit/utils/request_handlers/CurlRequestHandlerTest.php
test/unit/utils/request_handlers/FileGetContentsRequestHandlerTest.php

Update request handlers tests with coding standards

Update request handlers tests with coding standards

---

.phpcs.xml
test/unit/modified_vendor/SimpleHtmlDomTest.php

Update SinpleHtmlDomTest with coding standards

Update SinpleHtmlDomTest with coding standards

---

.phpcs.xml
src/wovn_helper.php

Update wovn_helper.php for coding standards

Update wovn_helper.php for coding standards

---

.phpcs.xml
src/wovnio/html/HtmlConverter.php
src/wovnio/html/HtmlReplaceMarker.php
src/wovnio/wovnphp/Utils.php

Limit scope of excluded rules
Put back rules excluded because of PHP 5.3 and ignore those only in the file where they need to be ignored/

Limit scope of excluded rules

---

src/version.php
src/wovn_interceptor.php
src/wovnio/modified_vendor/SimpleHtmlDom.php
src/wovnio/wovnphp/API.php
test/bootstrap.php

Move version out of API.php and bump it up to 0.1.11

Move version out of API.php and bump it up to 0.1.11

---

src/version.php
src/wovnio/utils/request_handlers/CurlRequestHandler.php
test/unit/utils/request_handlers/CurlRequestHandlerTest.php

Same as [[FIX] cURL timeout error](https://github.com/WOVNio/wordpress_plugin/pull/62)

[FIX] cURL timeout error

---

README.md

I added bug report item list to REAMDME.md for easy debugging.

[MISC]Add bug report item list to README

---

composer.json
test/unit/html/HtmlReplaceMakerTest.php

Same fix with the following PR.
https://github.com/WOVNio/wovnrb/pull/152
WOVN.php already have fix, but there are no tests.
So, I just add tests.

Add tests for addValue and revert

---

src/version.php

version up from 0.1.18 to 0.1.19

---

.circleci/config.yml
.gitignore
.htaccess
apache.yml
docker/HOWTO.md
htaccess_sample
scripts/phpunit.sh
src/version.php
src/wovn_helper.php
src/wovn_interceptor.php
test/unit/WovnHelperTest.php
wp_apache.yml

https://github.com/WOVNio/equalizer/issues/25125
- Delete `WOVNPHP_DEFAULT_INDEX_FILE`
- Add docker environment with Wordpress
- Add sample to not allow access `wovn.ini` to `htaccess_sample` 
- Add `.htaccess` to not allow access WOVN.php directly
- Reverse CircleCI tests order of PHP versions to find error version easily

[MISC]WOVN.php improvement

---

docker/HOWTO.md

Remove because it is relevant to the wovn user

Remove unnecessary explain for wovn users

---

src/version.php
src/wovnio/wovnphp/Utils.php
test/unit/UtilsTest.php

Document files (e.g. doc/xls) are not eligible for translation.

[HOTFIX] Adjust doc file regexp

---

README.en.md
README.ja.md

Added a description of the option to disable WOVN.PHP on AMP-enabled pages.

Added description of the `checkamp` parameter.

---

htaccess_sample
src/version.php

https://wovnio.atlassian.net/browse/ST-380
Add Khmer to default htaccess

Add Khmer to default htaccess

---

src/version.php

version up to 1.0.0

---

src/version.php
src/wovnio/html/HtmlConverter.php
test/unit/APITest.php
test/unit/html/HtmlConverterTest.php

https://wovnio.atlassian.net/browse/ST-340
Support for `data-` prefix for wovn attributes.

Support data- prefix for WOVN attributes

---

src/version.php

version up to 1.2.0

---

README.en.md
README.ja.md

https://wovnio.atlassian.net/browse/ST-514

Add document for custom domain pattern

---

src/wovn_interceptor.php
src/wovnio/html/HtmlConverter.php
src/wovnio/wovnphp/API.php
src/wovnio/wovnphp/Headers.php
test/unit/APITest.php
test/unit/HeadersTest.php
test/unit/UrlTest.php
test/unit/html/HtmlConverterTest.php

https://wovnio.atlassian.net/browse/ST-503
Small refactor with some renames that I feel are more descriptive.

rename lang->requestLang, pathLang -> urlLang

---

README.en.md
README.ja.md

Changed the old description of custom_domain to the new one

Updated documentation related to the custom_domain pattern.

---

htaccess_sample
src/version.php
src/wovnio/wovnphp/Lang.php
test/unit/LangTest.php

https://wovnio.atlassian.net/browse/ST-526
Add Sinhala and Tamil support

Add Tamil and Sinhala support

---

README.en.md
README.ja.md

Updated the README to include instructions on how to enable JSON format config file support.
The Japanese README needs to be translated. English content is added there temporarily.

Added information on how to enable JSON config usage

---

.gitignore
docker/public/testdir/testpage-dir.html
docker/public/testdir/testpage-redirect-destination.php
docker/public/testpage-redirect-origin.php
docker/public/testpage.html

https://wovnio.atlassian.net/browse/ST-612
Add test pages in preparation for expanded backend testing framework.

Add test pages in preparation for backend testing

---

src/version.php
src/wovn_interceptor.php
src/wovnio/wovnphp/Diagnostics.php

https://wovnio.atlassian.net/browse/ST-677
- added support for wovn.json configuration files
- added server env dump
- added support for custom wovn config file locations
- reduced DIR scan size limit to 1000 items (too huge an HTML file can cause display problems)
- added interpreted config dump

Improve diagnostic tools

---

src/version.php
src/wovnio/modified_vendor/SimpleHtmlDomNode.php
test/unit/modified_vendor/SimpleHtmlDomTest.php

Preview version of https://github.com/WOVNio/WOVN.php/pull/159

Fix detecting attribute logic

---

src/version.php
src/wovnio/html/HtmlConverter.php
src/wovnio/wovnphp/API.php
src/wovnio/wovnphp/Store.php
test/helpers/TestUtils.php
test/integration/WovnIndexSampleApacheTest.php
test/unit/APITest.php
test/unit/StoreTest.php
test/unit/html/HtmlConverterTest.php

https://wovnio.atlassian.net/browse/ST-823
Remove existing snippets.
Any delimiter can be used in PHP.
By using `@`, no need to escape `/`.

[ST-823] Remove existing snippets

---

src/version.php
src/wovnio/utils/request_handlers/AbstractRequestHandler.php

https://wovnio.atlassian.net/browse/ST-1215
Instead of form encoded payload, WOVN.php now sends JSON encoded payload.

switch to JSON encoded data

---

scripts/run_phpunit_tests.sh
src/version.php
src/wovnio/wovnphp/Logger.php

https://wovnio.atlassian.net/browse/ST-1349
Stop setting the global timezone setting to UTC.

[ST-1349] Stop setting global timezone to UTC by default.

---

src/version.php
src/wovnio/wovnphp/Lang.php

This replaces es-RA with es-AR

fix: replace es-RA with es-AR

---

src/version.php
src/wovnio/wovnphp/API.php
test/unit/APITest.php

https://wovnio.atlassian.net/browse/ST-2134
https://github.com/WOVNio/equalizer/pull/55201
https://github.com/WOVNio/html-swapper/pull/935
html swapper needs the browser url so it can pass it to equalizer for crawling purposes

feature: [ST-2134] send original request URL to html swapper

---

test/unit/html/HtmlConverterTest.php

Import tests from WOVNio/wovnjava#229.

test: Add tests to check multiple hidden inputs

---

src/version.php
src/wovnio/wovnphp/API.php
src/wovnio/wovnphp/Store.php
test/unit/APITest.php

https://wovnio.atlassian.net/browse/ST-2849

feat: [ST-2849] Add `preserve_relative_urls` setting

---

Makefile
docker/apache.yml
docker/apache/Dockerfile
docker/nginx/Dockerfile
docker/public/.htaccess
scripts/convert.sh
scripts/revert.sh
src/version.php
src/wovnio/wovnphp/API.php
test/unit/APITest.php

https://wovnio.atlassian.net/browse/ST-3320
https://github.com/WOVNio/html-swapper/pull/1044

feat: [ST-3320] Support page_status_code

---

.circleci/config.yml

Add test php8.4 config
