WOVNio/WOVN.php

src/wovnio/html/HtmlConverter.php, src/wovnio/wovnphp/API.php, src/wovnio/wovnphp/Headers.php, src/wovnio/wovnphp/Store.php, src/wovnio/wovnphp/Url.php, test/APITest.php, test/UrlTest.php, test/fixtures/basic_html/insert_hreflang_body.html, test/fixtures/basic_html/insert_hreflang_body_expected.html, test/fixtures/basic_html/insert_hreflang_expected.html, test/fixtures/basic_html/insert_hreflang_head_style.html, test/fixtures/basic_html/insert_hreflang_head_style_expected.html, test/fixtures/basic_html/insert_hreflang_html.html, test/fixtures/basic_html/insert_hreflang_html_expected.html, test/fixtures/basic_html/insert_hreflang_with_custom_lang_codes.html, test/fixtures/basic_html/insert_hreflang_with_custom_lang_codes_expected.html, test/fixtures/basic_html/insert_snippet_when_already_exist.html, test/fixtures/basic_html/insert_snippet_when_already_exist_expected.html, test/fixtures/basic_html/insert_with_exist_hreflang.html, test/fixtures/basic_html/insert_with_exist_hreflang_expected.html, test/fixtures/real_html/stack_overflow_hreflang.html, test/fixtures/real_html/stack_overflow_hreflang_expected.html, test/fixtures/real_html/stack_overflow_hreflang_html_entities_expected.html, test/html/HtmlConverterTest.php
- Stop using simple_html_dom because of memory leak issue
- Do not send request to API if current lang is default lang
- Inject snippet/hreflangs using regex (doing)
=> Stop using simple_html_dom because of memory leak issue

hack/run_integration_test.sh, integration_test/amp.php, integration_test/amp_expected.html, integration_test/wovn.ini, src/wovn_interceptor.php, src/wovnio/wovnphp/Store.php, src/wovnio/wovnphp/Utils.php, test/UtilsTest.php
Add setting for checking and ignoring AMP files
If the intercepted file is an AMP file, it can be ignored by WOVN.php and content should not be changed. Because WOVN.php interception is explicit most of the time (user controls what to intercept), I made it an option that is disabled by default.
Because WOVN.php avoids using HTML parser most of the time, and because this feature is disabled by default I am using regexps too.
=> Add setting for checking and ignoring AMP files

hack/run_integration_test.sh, integration_test/static.html, integration_test/static_expected.html, wovn_index_sample.php
Fix `wovn_index_sample.php` to not include query parameters during filepath lookup
Because `$_SERVER['REQUEST_URI']` may contain query parameters, looking for filepath to include may fail and will fallback to displaying content of index file instead of actual file.
=> Fix wovn_index_sample.php to not include query parameters during filepath lookup

src/wovnio/html/HtmlConverter.php, src/wovnio/wovnphp/API.php, src/wovnio/wovnphp/Headers.php, src/wovnio/wovnphp/Store.php, src/wovnio/wovnphp/Url.php, test/fixtures/basic_html/insert_hreflang_default_lang_alias.html, test/fixtures/basic_html/insert_hreflang_expected_default_lang_alias.html, test/fixtures/basic_html/insert_hreflang_expected_default_lang_alias_trailing_slash.html, test/fixtures/basic_html/insert_hreflang_expected_lang_alias.html, test/fixtures/basic_html/insert_hreflang_lang_alias.html, test/html/HtmlConverterTest.php
Relate: https://github.com/WOVNio/equalizer/issues/10291 (issue)
https://github.com/WOVNio/WOVN.php/pull/37
https://github.com/WOVNio/html-swapper/pull/167
https://github.com/WOVNio/equalizer/pull/10598
AT
If user set custome language aliases with default language code, should be do following behavior
```
en => en
zh-CHS => tc
```
- when /en/, display English content
- when /tc/, display simple Chinese and read local file en/dir/file (not dir/file)
- when /th/, display Thai content and read local file en/dir/file (not dir/file)
- in above three case, if html-swapper does not reply response, render hreflangs that include /en/, /tc/ and /th/
This PR include fix bug about trailing slash.
- keep trailing slash for hreflang
- keep trailing slash to send to html-swaper about url parameter
=> Default language code alias

src/wovnio/wovnphp/SSI.php, test/SSIWovnIndexSampleTest.php, test/WovnIndexSampleTest.php, wovn_index_sample.php
Evaluate PHP with SSI suppor
`file_get_contents` which is used for SSI support does not evaluate PHP
code within `<?php` and `?>`. This commit uses `include` instead of
`file_get_contents`, which evaluate PHP code.
=> Add PHP evaluation with SSI support

.circleci/config.yml, .gitignore, .phpcs.xml, composer.json, composer.lock
Start using coding standard for WOVN.php
This PR adds PHP_CodeSniffer with PSR2 ruleset in order to force the same coding standard on every `.php` file. PHP_CodeSniffer allows for customizing ruleset, we can include more rules as well as excluding those we don't want.
This PR aims for discussing/setting which standard to use. No code change is included in this PR (current files with lint errors or warning are ignored during analysis).
PSR2 specification: https://www.php-fig.org/psr/psr-2/
=> Coding Standard

.phpcs.xml
- Ease future PR reviews
- Add rules we already talked about (https://github.com/WOVNio/WOVN.php/pull/48#discussion_r216245788)
- Because we are compatible with PHP 5.3, we sometime use "_" for "private
visibility" because we cannot call actual private functions into anonymous
functions. Therefore I disabled the rule that forbid it.
- Because fixing all rules + changing indentation all at once make PRs
difficult to review, I disabled indentation rule temporarily.
- PSR2 does not enforce naming conventions outside of classes, but I
think we should use the same conventions accross the code so I added
rules for camelCased function names and variable name outside classes
too.
=> Changes to Code Standard Rules

.phpcs.xml, src/wovnio/html/HtmlConverter.php, src/wovnio/wovnphp/Lang.php, test/helpers/HeadersMock.php, test/unit/LangTest.php
Update Lang with coding standard
`Lang::$lang` did not have visibility and it is accessed from tests so it needed to be public. I also renamed it into `Lang::$index` instead of `Lang::$lang`. Note that it should be a constant, but PHP 5.3 forbids array constants.
I also fixed in-file rules ignore with latest (most-specific) syntax.
=> Update Lang with Coding Standard

src/wovnio/wovnphp/API.php, test/unit/APITest.php
Send every setting to translation API
In future, implementation of translation API may require settings set on backend side. For that reason, and to avoid setting specific settings every time and asking client to update WOVN.php, all settings are now sent to translation API.
=> Send every setting to translation API

src/wovnio/wovnphp/API.php, test/unit/APITest.php
Reverts WOVNio/WOVN.php#81
Settings are parsed as string at Translation API. Revert until fixed.
=> Revert "Send every setting to translation API"

README.md
Make doc more precise
Since it is important that path htaccess rules are on top of htaccess to prevent interfering with `-d` and `-f` checks, I added it in documentation.
=> Clarify that path htaccess rules should be put at begining of htaccess

src/wovnio/modified_vendor/SimpleHtmlDom.php
fix PHP 7.3 error on unescaped dash in regexp
=> Fix PHP 7.3 error on unescaped dash in regexp

src/wovnio/wovnphp/Utils.php, test/unit/UtilsTest.php
Like ZIP and TAR files, RAR and gziped files should not be intercepted.
=> Stop Intercepting .rar and .tar.gz files

src/version.php, src/wovnio/wovnphp/Store.php, test/unit/StoreTest.php
Support users that use custom lang aliases in their list of supported languages.
Some user mistake and input their custom language codes in the list of supported languages. This leads to invalid hreflangs being generated by WOVN.php. This change iterates through supported languages list and ensure the language codes are set to valid WOVN.php language codes, using user's custom lang aliases if necessary.
=> Support Custom Lang Aliases in `supported_langs`

README.md, src/version.php, src/wovnio/wovnphp/Headers.php, test/unit/HeadersTest.php
When WOVN.php serves a request behind a proxy and the request URI gets modified in the process, it will need to read the original request URI from a HTTP Header. The header name for original URI is `X-Forwarded-Request-Uri`, and it must be manually set by the user. See the README for an example of how set it.
The original client requested URI is needed in order to correctly identify the requested page, and is used for setting hreflang tags in the HTML content and for locating the correct translation data.
WOVN.php will only look at the `X-Forwarded-Request-Uri` header if `use_proxy = 1` is set in wovn.ini.
=> Support HTTP Header X-Forwarded-Request-Uri for when proxy is used

.circleci/config.yml
I added test target php versions using docker image similar to WOVN.php.
Wordpress plugin supports php 5.3 or higher.
=> [MISC]Add test target php versions

src/version.php, src/wovn_helper.php
Prevent interception errors due to CWD changed
When WOVN.php intercepts through wovn_index.php, CWD is the root because wovn_index.php is at the root. However, the file intercepted by WOVN.php is not necessary at the root and relative imports become broken. This PR set the CWD to the directory of the file intercepted.
=> Prevent Interception Errors Due to CWD Changed

README.md, src/wovn_interceptor.php, src/wovnio/wovnphp/Utils.php, test/unit/UtilsTest.php
Change `ignore_paths` setting to only match against URLs from the beginning of the path.
Leading and trailing slash in `ignore_paths` values are effectively ignored, and the values are interpreted as if starting with a leading slash and ending with no trailing slash.
Therefore, the following four values will have the exact same result
```
global
/global
global/
/global/
```
The values above will match URLs of the following form
```
example.com/global
example.com/global/
example.com/global/images/dog.png
```
And not match URLs like
```
example.com/events/global
example.com/globalized
```
=> Restrict ignore paths matching

README.md, htaccess_sample, src/version.php, src/wovnio/html/HtmlConverter.php, src/wovnio/wovnphp/API.php, src/wovnio/wovnphp/Store.php, test/fixtures/basic_html/insert_hreflang_expected_multi_noindex_langs.html, test/fixtures/basic_html/insert_hreflang_expected_noindex_langs.html, test/unit/APITest.php, test/unit/StoreTest.php, test/unit/html/HtmlConverterTest.php
https://wovnio.atlassian.net/browse/IS-711
I added `no_index_langs` and you can set it in `wovn.ini` as below.
`no_index_langs` can be set with custom_lang_aliases lang.
```
no_index_langs[] = en
```
if `no_index_langs` include `en`, WOVN.php will behave like the followings.
- Add `<meta name="robots" content="noindex">` for English pages
- Don't add hreflang for English for all pages
- Add `no_index_langs` param for request to html-swapper
=> Add noindex for specified languages

README.en.md, README.ja.md, src/version.php, src/wovnio/wovnphp/Utils.php, test/unit/UtilsTest.php
When I do a `SetEnv` in `.htaccess`, it means `$_SERVER['WOVN_CONFIG']`.
Therefore, change from `$_ENV` to `$_SERVER`.
After this, I'll try to add some additional integration tests include `.htaccess`.
=> [Hotfix] Change env variable name for WOVN_CONFIG

src/version.php, src/wovnio/wovnphp/Headers.php
https://wovnio.atlassian.net/browse/SUP-246
`apache_response_headers` obviously only exists on Apache servers.
Redirects to `/dir/page` etc need to be translated to `/en/dir/page` by WOVN.php
=> Translate redirects on non-apache webservers.

test/integration/UrlPathPatternTest.php
When user uses `wovn_index.php` with `path` pattern, adding `RewriteRule ^/?(?:ar|...)($|/.*$) $1 [L]` to `.htaccess` is unnecessary.
Because all URL will be redirected to `wovn_index.php`.
Adding `RewriteRule ^/?(?:ar|...)($|/.*$) $1 [L]` is necessary, when user uses `wovn_intercepter.php`.
=> Fix integration tests

README.en.md, README.ja.md, src/wovnio/wovnphp/Headers.php, src/wovnio/wovnphp/Store.php, test/unit/HeadersTest.php, test/unit/StoreTest.php
This refers to the `query[]=foo` setting that was apparently a thing. It was added on the very first commit of WOVN.php, but I am not convinced it is actually used. I am assuming this was carried over from the old wovnphp that did not use html swapper.
Equalizer _does_ have a query parameter feature, where you can specify which query parameters should be considered a "unique" page in our system. However, this is no longer any concern of backends. This logic is done in the `js_data` request during auto page add logic (the fact that the widget does not have any code for this feature is also telling). 
WOVN.php already sends the full URL including query params to HTML swapper (regardless of this setting). Then HTML swapper forwards this to the js_data request. So I am not sure that this …
=> Remove query feature

.gitignore, src/wovnio/wovnphp/Headers.php, src/wovnio/wovnphp/Utils.php
`$env['REQUEST_URI']` should always be available. It is only missing when running PHP in CLI mode which is not the case for web servers. So I think this is a useless assignment.
After reading on https://www.php.net/manual/en/reserved.variables.server.php, I think this was not implemented correctly anyway. $_SERVER['PATH_INFO'] does not contain the full request path, so I suspect this code has not really been used.
I would like to reduce the number of environment variables we access.
=> remove REQUEST_URI fallback

src/version.php, src/wovnio/html/HtmlConverter.php, src/wovnio/modified_vendor/SimpleHtmlDomNode.php, src/wovnio/wovnphp/CookieLang.php, test/helpers/StoreAndHeadersFactory.php, test/unit/html/HtmlConverterTest.php, test/unit/modified_vendor/SimpleHtmlDomTest.php
`$node->getAttribute('wovn-ignore')` is falsy, even if the attribute exists.
I added `hasAttribute` method to check having `wovn-ignore` or not.
```
<span wovn-ignore>xxx</span> -> marked
<span wovn-ignore="true">xxx</span> -> marked
<span wovn-ignore="">xxx</span> -> not marked (should mark)
```
=> Fix wovn-ignore mark

docker/HOWTO.md, docker/nginx/Dockerfile, docker/test.yml, docker/wp_apache.yml, makefile, test/helpers/TestUtils.php
https://wovnio.atlassian.net/browse/ST-561
By this PR, you can set break point via XDebug.
You need to run tests inside docker, because of setup XDebug.
=> Enable XDebug in tests

.phpcs.xml, README.en.md, README.ja.md, makefile, src/version.php, src/wovnio/html/HtmlConverter.php, src/wovnio/wovnphp/API.php, src/wovnio/wovnphp/Store.php, test/integration/InsertHreflangsTest.php, test/unit/APITest.php, test/unit/html/HtmlConverterTest.php
https://wovnio.atlassian.net/browse/ST-572
Don't touch hreflang, if `insert_hreflangs` is false.
WOVN.php has two logic to insert hreflang.
I removed it from `convertToAppropriateBodyForApi` and changed to only use `insertSnippetAndHreflangTags`.
html-swapper part:
https://github.com/WOVNio/html-swapper/pull/541
=> Add insert_hreflangs feature

src/version.php, src/wovn_interceptor.php, src/wovnio/wovnphp/API.php, src/wovnio/wovnphp/Headers.php, src/wovnio/wovnphp/RequestOptions.php, src/wovnio/wovnphp/Store.php, test/unit/APITest.php, test/unit/RequestOptionsTest.php
https://wovnio.atlassian.net/browse/ST-589
Adds support for `wovnDisable` URL parameter which if enabled will cause the library to not swap the request.
Also adds a Debug Mode setting that enables two URL parameters:
`wovnCacheDisable`: inserts a timestamp into the API call url to circumvent Fastly caching
`wovnDebugMode`: adds {“debug_mode”: “true”} to API call request payload, and add a timestamp to the API call to circumvent Fastly cache.
Usage:
All parameters can enabled by adding to the URL either without a value (e.g. `?lang=ja&wovnCacheDisable`) or with any value other than the string `'false'` (e.g. `?lang=ja&wovnDebugMode=true`).
=> Add debug request parameters

docker/apache/Dockerfile, docker/nginx/Dockerfile
Fixes Xdebug version at 2.9.0.
Newer versions of Xdebug do not work with the current configuration and will result in your debugger not connecting to the test site.
=> Fix Xdebug version at 2.9.0

src/version.php, src/wovnio/wovnphp/custom_domain/CustomDomainLangUrlHandler.php, test/unit/custom_domain/CustomDomainLangUrlHandlerTest.php
In CustomDomainUrlHandler.php, a back-reference is used to replace part of the URL. 
Originally, it was. `"$1${replacement}$3"`. This works fine in most situations (how is this even possible?). But when the URL starts with the number `1`, that `1` will be incorrectly removed.
e.g. `https://123.test.com` -> `https://23.replacement.com` (NG)
Now, the new back-reference is in the `${1}` and `${3}` format.
=> [Fix]incorrect regex backref

src/version.php, src/wovnio/wovnphp/Headers.php, test/unit/HeadersTest.php, test/unit/UrlTest.php
This PR fixes an issue where the host name of a request cannot be reliably determined when determining the request language.
Originally the server environment variable `SERVER_NAME` is used to determine the host name of a request, and this host name is subsequently used to reconstruct a URL for later processing. When a user is using some cgi interfaces, there is a chance that `SERVER_NAME` does not reflect the actual host name.
To fix this, `HTTP_HOST` is used instead, which always reflects the `Host` header of the incoming request. This should be a much more reliable way of determining the host name.
=> [Fix] Change use of SERVER_NAME to HTTP_HOST

README.en.md, src/wovnio/wovnphp/Logger.php, src/wovnio/wovnphp/Store.php
This PR aims to fix a bug where WOVN.php's logger always outputs logs to PHP's system logger, even if no `logging` setting is configured in the config file.
**Old behavior:**
The Wovn logger is always set to active upon initialization, with default destination as PHP System Logger.
**New behavior:**
the Wovn logger is only set to active if `logging` setting is configured in the config file.
This PR does not introduce new behaviors and is backward compatible.
=> Fixed logger default behavior: logger is now off by default unless logging is set.

docker/public/page.php, docker/public/redirecting_page.php, docker/public/redirection_target.php
This PR standardizes the available urls for testing. For PHP pages, they all ends in `.php`.
The following standard URLs are made available:
- `/redirecting_page.php` : this will redirect to `/redirection_target.php`
- `/page.php` : a simple html test page
Also, the following .gitignore config doesn't do anything to allow individual files within `/docker/` be tracked...
```
/docker/*
!/docker/apache/*
!/docker/nginx/*
!/docker/HOWTO.md
!/docker/php.ini
```
from git documentaiton:
> It is not possible to re-include a file if a parent directory of that file is excluded. Git doesn’t list excluded directories for performance reasons, so any patterns on contained files have no effect, no matter where they are defined.
I'm not sure why they were added but I'm keeping them for now.
=> added new test pages.

docker/apache.yml, docker/public/.htaccess, docker/public/custom_index.php, docker/public/wovn.ini, docker/public/wovn_index.php
https://wovnio.atlassian.net/browse/ST-901
This PR is a quality of life PR that improves debugging using the docker environment.
Most notably, this PR adds the ability to send a request to any route prefixed by`/custom_response`, and dictate what the response should be.
You can decide:
- Response headers
- Response HTTP status code
- Response body
You need to include a JSON body with such requests:
```
{
"response": {
"body": "foo2",
"content-type": "text/html",
"status": 200,
"headers": { "X-WovnTest": "Foo" }
}
}
```
Theoretically speaking, content-type is also a header, but it is included in its separate field.
In addition to this universal route, access to normal paths (files) are also supported, as long as they do not contain `custom_response` in their name or path.
**Changes made:** …
=> [ST-901] Added support for custom requests.

docker/apache/Dockerfile, src/version.php, src/wovnio/wovnphp/SSI.php, test/integration/SSIWovnIndexSampleTest.php
https://wovnio.atlassian.net/browse/SUP-1015
WOVN supports SSI(Server Side Include).
When SSI is found by regular expression, WOVN.php tries to load included file.
This issue is caused by not flexible regular expression, and it failed to found SSI.
This PR fix:
- Fix reguler expression
- Add mod_include of Apache for Dockerfile to use SSI
When you try this one, please be careful about the followings.
- rebuild docker image by `make build` to include mod_include
- configure SSI in wovn_index.php
- Add the following to .htaccess to enable SSI
```
Options +Includes
AddType text/html .html
AddOutputFilter INCLUDES .html
```
Then, you will be able to include files by ``.
=> [SUP-1015] Change regular expression to support SSI

docker/public/custom_index.php
To be the same as other backends for testing, you should be able to send 
```
{
"response": {
"body": "<html><body>foo</body></html>",
"content-type": "text/html",
"status": 201,
"headers": { "X-WovnTest": "Foo" }
}
}
```
and receive the expected status code.
PHP 5.3 makes it a little difficult to set the status code. Not that this docker supports 5.3 but I thought i'd make it compatible just in case.  I used the strategy in https://stackoverflow.com/a/12018482
=> tests: Implement status code for custom responses in test docker

src/version.php, src/wovnio/wovnphp/Store.php, test/helpers/StoreAndHeadersFactory.php
https://wovnio.atlassian.net/browse/ST-1363
`disable_api_request_for_default_lang` was `false` by default.
- false: Do request to html-swapper for default lang
- true: Don'T request to html-swapper for default lang
It is expensive for WOVN.php to make an API request for default lang.
So, this PR make it `true` as default.
=> [ST-1363] Change disable_api_request_for_default_lang default to true

src/wovnio/utils/request_handlers/FileGetContentsRequestHandler.php
https://wovnio.atlassian.net/browse/ST-1340
- Add more detail of error by using `error_get_last()` to `X-Wovn-Error` header.
Header will have `([error-type] - [error-in-response-for-html-swapper])`.
e.g. `X-Wovn-Error: [fgc] Request failed (2 - HTTP\\/1.1 500 Internal Server Error)`
- error-type: error type code (https://www.php.net/manual/en/errorfunc.constants.php)
- error-in-response-for-html-swapper: error message in `$http_response_header[0]` (https://www.php.net/manual/en/reserved.variables.httpresponseheader.php)
- Log error message in `error_get_last()`.
=> [ST-1340] Show more detail of file_get_contents error

src/version.php, src/wovnio/html/HtmlConverter.php, src/wovnio/modified_vendor/SimpleHtmlDomNode.php
The SimpleHtmlDOM fork we use suffers from segfaults if the number of nodes in the DOM is high. The segfaults are caused by the `$var -> null;` assignments. Since those are only need for PHP5, a version check is implemented so that this does not affect users of other versions of PHP.
=> Executes memory free only for PHP5.

src/version.php, src/wovnio/wovnphp/Headers.php, src/wovnio/wovnphp/Url.php, test/helpers/EnvFactory.php, test/unit/HeadersTest.php, test/unit/UrlTest.php
https://wovnio.atlassian.net/browse/SUP-1505?focusedCommentId=49454
This can happen with custom domain + source pattern
```
custom_domain_langs: {
en: { url: "site.com/global/" },
fr: { url: "site.com/french/", source: "site.com/french/ },
}
```
`site.com/french/page.php` is a different file from `site.com/global/page.php` on disk, and the customer may send a redirect between them.
```
1. Request: https://site.com/french/page.php Lang code: fr
2. Customer redirect: https://site.com/global/page.php
3. WOVN tries to convert redirect to "fr" to maintain language: https://site.com/french/page.php
Redirect loop.
```
I want to try and prevent this by checking after step 3, did we convert the redirect to the same URL as the original request? If so, don't change the location.
=> [SUP-1505] Fix redirect loop with custom domain + source pattern.

src/version.php, src/wovnio/utils/request_handlers/FileGetContentsRequestHandler.php
https://wovnio.atlassian.net/browse/ST-1405
In certain installations of PHP, the normally predefined variable `http_response_header` is left undefined. This change initializes it as an empty array first.
=> [ST-1405] initialize http_response_header with empty array before returning

docker/HOWTO.md, src/version.php, src/wovnio/html/HtmlConverter.php, test/unit/html/HtmlConverterTest.php
https://wovnio.atlassian.net/browse/ST-1732
The flow of issue is:
1. Customer set `wovn-ignore` attribute for `title` tag. e.g. `<title wovn-ignore>こんにちは</title>`
2. WOVN.php add replace marker for ignored element. e.g. `<title wovn-ignore></title>`
3. html-swapper escapes. e.g. `<title wovn-ignore="">&lt;!-- __wovn-backend-ignored-key-0 --&gt;</title>` 
4. WOVN.php tris to revert it with original value, but `` doesn't match with `&lt;!-- __wovn-backend-ignored-key-0 --&gt;` and it would remain as marker.
Escape in html-swapper is not wrong, because title tag is just text, so title tag should not include comment node.
https://html.spec.whatwg.org/multipage/semantics.html#the-title-element
This PR changes marker for title tag to not have character which is escaped by html-swapper.
With …
=> fix: [ST-1732] Change replace marker for title tag

.gitignore, docker/public/ssi_included.html, docker/public/ssi_page.html, docker/public/wovn_index.php, src/version.php, src/wovn_helper.php, src/wovnio/wovnphp/SSI.php, test/integration/SSIWovnIndexSampleTest.php, wovn_index_sample.php
https://wovnio.atlassian.net/browse/ST-1828
Doing `include` inside of a function means the included files inherits the scope of the function. Customers may be declaring global variables inside of the included php file, but when included by `wovn_helper`, they become variables of our function scope, not global scope.
I changed the code to `include` at the top level. This means we have to be careful about variable naming since everything is in the global scope. I renamed all variables and functions to have a `wovn` prefix.
Refactor: I re-arranged the SSI code to be based on a `$wovn_use_ssi` variable rather than have commented out code that the user must uncomment. Because of the changes to fix this bug, it becomes confusing to explain which lines need to be commented out for SSI. It is …
=> fix: [ST-1828] wovn_helper now includes files in the global scope

README.en.md, README.ja.md, docker/HOWTO.md, src/version.php, src/wovnio/html/HtmlConverter.php, src/wovnio/wovnphp/API.php, src/wovnio/wovnphp/Store.php, test/fixtures/basic_html/insert_hreflang_expected_multi_nohreflang_langs.html, test/fixtures/basic_html/insert_hreflang_expected_nohreflang_langs.html, test/integration/UrlQueryPatternTest.php, test/unit/APITest.php, test/unit/StoreTest.php, test/unit/html/HtmlConverterTest.php
https://wovnio.atlassian.net/browse/ST-1887
Needed to allow a new scenario with `custom_domain` where the default lang is not configured and will never be accessed by users. `no_hreflang_langs` acts the same as `no_index_langs` except it will not add a `noindex` tag
```
"url_pattern_name": "custom_domain",
"custom_domain_langs": {
"ja": {
"source": "local-php.com/japanese",
"url": "local-php.com/japanese"
},
"fr": {
"source": "local-php.com/french",
"url": "local-php.com/french"
}
},
"default_lang": "en",
"supported_langs": [
"ja",
"fr"
],
"no_hreflang_langs": [
"en"
],
```
Related PRs: https://github.com/WOVNio/html-swapper/pull/877 https://github.com/WOVNio/equalizer/pull/53371
=> feature: [ST-1887] Add no_hreflang_langs setting

docker/test.Dockerfile
Some PHP version tests start failing because of test environment setup.
https://app.circleci.com/pipelines/github/WOVNio/WOVN.php/825/workflows/277cc41e-687d-4337-9548-db816fdc5f85
`apt-get` command doesn't work for OS which depends on jessie. The following command update targets of apt-get.
```
echo "deb http://deb.debian.org/debian jessie main" > "/etc/apt/sources.list"; \
echo "deb http://security.debian.org jessie/updates main" >> "/etc/apt/sources.list"; \
```
It seems the targets were updated. This PR changed to refer archived packages. Like the followings.
```
echo "deb http://archive.debian.org/debian/ stretch main" > "/etc/apt/sources.list"; \
echo "deb http://archive.debian.org/debian-security stretch/updates main" >> "/etc/apt/sources.list"; \
```
=> fix: Fix test for older PHP versions

src/version.php, src/wovnio/wovnphp/Headers.php, test/unit/HeadersTest.php
https://wovnio.atlassian.net/browse/SUP-2248
Adds support for `CloudFront-Forwarded-Proto` header, which CloudFront uses instead of `X-Forwarded-Proto`.
Ref.: [Amazon CloudFront docs](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html#request-custom-headers-behavior)
=> feat: [SUP-2248] Add support for `HTTP_CLOUDFRONT_FORWARDED_PROTO`

src/version.php, src/wovnio/html/HtmlConverter.php, src/wovnio/modified_vendor/SimpleHtmlDomNode.php, test/unit/html/HtmlConverterTest.php, test/unit/modified_vendor/SimpleHtmlDomTest.php
Fixes logic where `0` is not ignored and sent to html-swapper as-is.
Before (text sent to html-swapper):
```
<input type="hidden" value="0">
```
After:
```
<input type="hidden" value="__wovn-backend-ignored-key-${SOME_INCREMENTAL_KEY}">
```
PHP considers `'0'` string as `false` when converted to boolean (ref. [docs](https://www.php.net/manual/en/language.types.boolean.php#language.types.boolean.casting)).
=> fix: [ST-2184] Hidden input with "0" value is not ignored

src/version.php, src/wovnio/html/HtmlConverter.php, src/wovnio/wovnphp/Headers.php, src/wovnio/wovnphp/custom_domain/CustomDomainLang.php, test/unit/html/HtmlConverterTest.php
https://wovnio.atlassian.net/browse/ST-2232
https://github.com/WOVNio/html-swapper/pull/968
Some customers are using refresh meta tags to trigger refreshes. We want to translate this redirect URL similar to a normal redirect.
`<meta http-equiv="refresh" content="0;URL=/international/index.html#anchor02">`
=> feature: [ST-2232] support meta refresh tags

README.en.md, README.ja.md, src/version.php, src/wovnio/utils/request_handlers/CurlRequestHandler.php, src/wovnio/wovnphp/Store.php, test/unit/StoreTest.php
https://wovnio.atlassian.net/browse/ST-2444
Support connecting to wovn servers via HTTP proxy. Only supported for curl.
Didn't test with an actual proxy server but curl reported this error so the setting is being applied correctly
```
curl_error($curl_session)
"Failed to connect to proxy.com port 7979: Connection timed out"
```
=> feature: add outbound_proxy_host/port settings, to support HTTP proxy via curl

.circleci/config.yml, scripts/run_phpunit_tests.sh, src/version.php, src/wovnio/utils/request_handlers/AbstractRequestHandler.php, src/wovnio/wovnphp/custom_domain/CustomDomainLangUrlHandler.php, test/integration/CookieLangTest.php, test/integration/InsertHreflangsTest.php, test/integration/SSIWovnIndexSampleTest.php, test/integration/UrlCustomDomainPatternTest.php, test/integration/UrlPathPatternTest.php, test/integration/UrlQueryPatternTest.php, test/integration/UrlSubdomainPatternTest.php, test/integration/WovnIndexSampleApacheTest.php, test/integration/WovnIndexSampleTest.php, test/unit/HeadersTest.php, test/unit/StoreTest.php
https://wovnio.atlassian.net/browse/ST-2960
Changes:
- Fixes the following deprecations:
- "Deprecate ${} string interpolation" (see [PHP RFC](https://wiki.php.net/rfc/deprecate_dollar_brace_string_interpolation))
- "Deprecate dynamic properties" (see [PHP RFC](https://wiki.php.net/rfc/deprecate_dynamic_properties))
- Adds tests for PHP 8.1 to 8.3
=> refactor: [ST-2960] Fix deprecations

src/version.php, src/wovnio/wovnphp/Headers.php, test/integration/CookieLangTest.php, test/unit/HeadersTest.php
https://wovnio.atlassian.net/browse/ST-3186
equivalent of https://github.com/WOVNio/proxy/pull/158/
We will now prefer the cookie language over the request language in all cases. If you have a language cookie different to the request lang, and this feature turned on, we will redirect to it.
=> fix: [ST-3186] use_cookie_lang now redirects for default + target lang cookies
